version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    links:
      - mongo
    networks:
      paultest:
        aliases:
         - app
  mongo:
    container_name: mongo
    image: mongo
    networks:
      paultest:
        aliases:
         - mongo
    ports:
      - "27017:27017"


networks:
  paultest:
    external: true